apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-calc
  template:
    metadata:
      labels:
        app: web-app-calc
    spec:
      containers:
        - name: web-app-calc
          image: sasaolu/web-apps:calculator
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service-calc
spec:
  type: LoadBalancer
  selector:
    app: web-app-calc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
