apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic-calc
  template:
    metadata:
      labels:
        app: magic-calc
    spec:
      containers:
        - name: magic-calc
          image: sasaolu/web-apps:magic-calculator
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  type: LoadBalancer
  selector:
    app: magic-calc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
