apiVersion: apps/v1
kind: Deployment
metadata:
  name: tindog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tindog
  template:
    metadata:
      labels:
        app: tindog
    spec:
      containers:
        - name: tindog
          image: sasaolu/web-apps:tindog
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tindog-service
spec:
  type: LoadBalancer
  selector:
    app: tindog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
